### ISSUE TITLE
MMD Tools 2.9.2 doesn't work with blender 2.92

### ISSUE THREAD

**Issue by le-shiro** [MMD-Blender/blender_mmd_tools#330]
I recently downgraded from Blender 3.6 to Blender 2.92 in order to address certain issues related to proportion editing.

However, I am currently encountering an issue when trying to install MMD Tools 2.9.2. The addon fails to enable and produces the following error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\33784\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_tools\__init__.py", line 25, in <module>
    from mmd_tools import properties
  File "C:\Users\33784\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_tools\properties\__init__.py", line 110, in <module>
    __patch(__properties)
  File "C:\Users\33784\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mmd_tools\properties\__init__.py", line 67, in __patch
    def __patch_override(prop: bpy.props._PropertyDeferred):
AttributeError: module 'bpy.props' has no attribute '_PropertyDeferred'

I would prefer to remain on Blender 2.92 for my current workflow, so I would appreciate any guidance on how to resolve this issue while staying on this version.

Thank you in advance for your help.

**Comment by ulyssas** [comment]
Why not use 2.93 LTS, instead of 2.92? Older MMD Tools version strings have nothing to do with Blender versions.

| Blender Version | MMD Tools Version | MMD UuuNyaa Tools Version |
| :-------------- | :---------------- | :------------------------ |
| Blender 4.2-5.1 |  MMD Tools v4.x   |   MMD Tools Append v4.x   |
|   Blender 3.6   | MMD Tools v2.10.3 |   UuuNyaa Tools v1.8.0    |
|  Blender 2.93   | MMD Tools v2.10.3 |   UuuNyaa Tools v1.7.2    |
|  Blender 2.83   | MMD Tools v2.5.1  |   UuuNyaa Tools v1.6.0    |

**Comment by ulyssas** [comment]
Or you could use [powroupi's version](https://github.com/powroupi/blender_mmd_tools). Either way, you should be using 2.93 over 2.92 if the issue doesn't occur in 2.93 LTS. LTS means it's much more stable.

**Comment by ulyssas** [comment]
@le-shiro Did you solve the issue?

**Comment by ulyssas** [comment]
I will close this for now. Feel free to reopen if you still have issues.
